# Generated by Django 3.2.5 on 2021-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
