# Generated by Django 3.2.5 on 2021-07-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210719_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_questions',
            field=models.ManyToManyField(blank=True, related_name='previous_choices', to='polls.Question'),
        ),
    ]
